---
- name: Testing Handlers
  hosts: all

  tasks:
  - name: Install VLC
    win_chocolatey:
      name: vlc
      state: present
    notify:
    - reboot server

  - name: Failing the task
    fail:
       msg: failing the task as testing required

  handlers:
  - name: reboot server
    win_reboot: